// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_adap_tbl
List build_adap_tbl(double phi1, double phi2, double a0, double b0, int N, int m, Nullable<NumericMatrix> loss);
RcppExport SEXP _adaptBOIN_build_adap_tbl(SEXP phi1SEXP, SEXP phi2SEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP NSEXP, SEXP mSEXP, SEXP lossSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type loss(lossSEXP);
    rcpp_result_gen = Rcpp::wrap(build_adap_tbl(phi1, phi2, a0, b0, N, m, loss));
    return rcpp_result_gen;
END_RCPP
}
// run_scenario_cpp
List run_scenario_cpp(NumericVector pi_r, int design, List atbl, List p, int n_sim, int base_seed);
RcppExport SEXP _adaptBOIN_run_scenario_cpp(SEXP pi_rSEXP, SEXP designSEXP, SEXP atblSEXP, SEXP pSEXP, SEXP n_simSEXP, SEXP base_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pi_r(pi_rSEXP);
    Rcpp::traits::input_parameter< int >::type design(designSEXP);
    Rcpp::traits::input_parameter< List >::type atbl(atblSEXP);
    Rcpp::traits::input_parameter< List >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP);
    Rcpp::traits::input_parameter< int >::type base_seed(base_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_scenario_cpp(pi_r, design, atbl, p, n_sim, base_seed));
    return rcpp_result_gen;
END_RCPP
}
// prior_mean_curve
List prior_mean_curve(int K, int J);
RcppExport SEXP _adaptBOIN_prior_mean_curve(SEXP KSEXP, SEXP JSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    rcpp_result_gen = Rcpp::wrap(prior_mean_curve(K, J));
    return rcpp_result_gen;
END_RCPP
}
// aboin_bounds_cpp
NumericVector aboin_bounds_cpp(double phi0, int n, double delta1, double delta2, double g1, double g2, int N0, double fixed_le, double fixed_ld);
RcppExport SEXP _adaptBOIN_aboin_bounds_cpp(SEXP phi0SEXP, SEXP nSEXP, SEXP delta1SEXP, SEXP delta2SEXP, SEXP g1SEXP, SEXP g2SEXP, SEXP N0SEXP, SEXP fixed_leSEXP, SEXP fixed_ldSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< double >::type delta2(delta2SEXP);
    Rcpp::traits::input_parameter< double >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< double >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< int >::type N0(N0SEXP);
    Rcpp::traits::input_parameter< double >::type fixed_le(fixed_leSEXP);
    Rcpp::traits::input_parameter< double >::type fixed_ld(fixed_ldSEXP);
    rcpp_result_gen = Rcpp::wrap(aboin_bounds_cpp(phi0, n, delta1, delta2, g1, g2, N0, fixed_le, fixed_ld));
    return rcpp_result_gen;
END_RCPP
}
// mtpi_actions_cpp
IntegerMatrix mtpi_actions_cpp(int N, int m, double phi1, double phi2, double a0, double b0);
RcppExport SEXP _adaptBOIN_mtpi_actions_cpp(SEXP NSEXP, SEXP mSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(mtpi_actions_cpp(N, m, phi1, phi2, a0, b0));
    return rcpp_result_gen;
END_RCPP
}
// mtpi2_actions_cpp
IntegerMatrix mtpi2_actions_cpp(int N, int m, double phi1, double phi2, double a0, double b0);
RcppExport SEXP _adaptBOIN_mtpi2_actions_cpp(SEXP NSEXP, SEXP mSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< double >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(mtpi2_actions_cpp(N, m, phi1, phi2, a0, b0));
    return rcpp_result_gen;
END_RCPP
}
// one_trial
List one_trial(NumericVector pi_r, int design, List atbl, List p, int seed);
RcppExport SEXP _adaptBOIN_one_trial(SEXP pi_rSEXP, SEXP designSEXP, SEXP atblSEXP, SEXP pSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pi_r(pi_rSEXP);
    Rcpp::traits::input_parameter< int >::type design(designSEXP);
    Rcpp::traits::input_parameter< List >::type atbl(atblSEXP);
    Rcpp::traits::input_parameter< List >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(one_trial(pi_r, design, atbl, p, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adaptBOIN_build_adap_tbl", (DL_FUNC) &_adaptBOIN_build_adap_tbl, 7},
    {"_adaptBOIN_run_scenario_cpp", (DL_FUNC) &_adaptBOIN_run_scenario_cpp, 6},
    {"_adaptBOIN_prior_mean_curve", (DL_FUNC) &_adaptBOIN_prior_mean_curve, 2},
    {"_adaptBOIN_aboin_bounds_cpp", (DL_FUNC) &_adaptBOIN_aboin_bounds_cpp, 9},
    {"_adaptBOIN_mtpi_actions_cpp", (DL_FUNC) &_adaptBOIN_mtpi_actions_cpp, 6},
    {"_adaptBOIN_mtpi2_actions_cpp", (DL_FUNC) &_adaptBOIN_mtpi2_actions_cpp, 6},
    {"_adaptBOIN_one_trial", (DL_FUNC) &_adaptBOIN_one_trial, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_adaptBOIN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
