# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_adap_tbl <- function(phi1, phi2, a0, b0, N, m, loss = NULL) {
    .Call(`_adaptBOIN_build_adap_tbl`, phi1, phi2, a0, b0, N, m, loss)
}

run_scenario_cpp <- function(pi_r, design, atbl, p, n_sim, base_seed) {
    .Call(`_adaptBOIN_run_scenario_cpp`, pi_r, design, atbl, p, n_sim, base_seed)
}

prior_mean_curve <- function(K, J) {
    .Call(`_adaptBOIN_prior_mean_curve`, K, J)
}

aboin_bounds_cpp <- function(phi0, n, delta1, delta2, g1, g2, N0, fixed_le, fixed_ld) {
    .Call(`_adaptBOIN_aboin_bounds_cpp`, phi0, n, delta1, delta2, g1, g2, N0, fixed_le, fixed_ld)
}

mtpi_actions_cpp <- function(N, m, phi1, phi2, a0, b0) {
    .Call(`_adaptBOIN_mtpi_actions_cpp`, N, m, phi1, phi2, a0, b0)
}

mtpi2_actions_cpp <- function(N, m, phi1, phi2, a0, b0) {
    .Call(`_adaptBOIN_mtpi2_actions_cpp`, N, m, phi1, phi2, a0, b0)
}

one_trial <- function(pi_r, design, atbl, p, seed) {
    .Call(`_adaptBOIN_one_trial`, pi_r, design, atbl, p, seed)
}

