# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build the adaptive decision table (C++)
#'
#' Computes the Bayes action for every achievable \code{(n, s)} pair under the
#' supplied loss matrix, returning a list indexed by cohort size.
#'
#' @param phi1,phi2 Lower and upper equivalence-interval bounds.
#' @param a0,b0 Beta prior parameters for the escalation posterior.
#' @param N Maximum sample size.
#' @param m Cohort size.
#' @param loss Optional 3 by 3 loss matrix; \code{NULL} uses the symmetric
#'   default. Rows are actions (escalate, stay, de-escalate) and columns are
#'   states (under, target, over).
#' @return A named list; element \code{"n"} holds the action codes
#'   (0 = escalate, 1 = stay, 2 = de-escalate) for \code{s = 0, ..., n}.
#' @export
build_adap_tbl <- function(phi1, phi2, a0, b0, N, m, loss = NULL) {
    .Call(`_adaptBOIN_build_adap_tbl`, phi1, phi2, a0, b0, N, m, loss)
}

#' Simulate one scenario (C++)
#'
#' @param pi_r True DLT probabilities, one per dose.
#' @param design Integer design code; see \code{\link{design_codes}}.
#' @param atbl Decision table from \code{\link{adapt_table}}.
#' @param p Parameter list from \code{\link{adapt_params}}.
#' @param n_sim Number of simulated trials.
#' @param base_seed Base seed; trial \code{i} uses \code{base_seed + i}.
#' @return A list of aggregated operating characteristics.
#' @export
run_scenario_cpp <- function(pi_r, design, atbl, p, n_sim, base_seed) {
    .Call(`_adaptBOIN_run_scenario_cpp`, pi_r, design, atbl, p, n_sim, base_seed)
}

#' Bernstein prior mean curve (C++)
#'
#' @param K Bernstein polynomial degree.
#' @param J Number of dose levels.
#' @return A list with the prior mean curve, the prior-mean distances to the
#'   target, and the marginal prior means of the coefficients.
#' @export
prior_mean_curve <- function(K, J) {
    .Call(`_adaptBOIN_prior_mean_curve`, K, J)
}

#' Simulate a single trial (C++)
#'
#' Unlike \code{\link{run_scenario_cpp}} this returns per-dose detail, which is
#' what the allocation diagnostics use.
#'
#' @inheritParams run_scenario_cpp
#' @param seed Random seed for this trial.
#' @return A list including \code{n_vec}, \code{s_vec}, \code{elim_vec} and the
#'   selected dose.
#' @export
one_trial <- function(pi_r, design, atbl, p, seed) {
    .Call(`_adaptBOIN_one_trial`, pi_r, design, atbl, p, seed)
}
